@startuml

title __DATABASE's Class Diagram__\n

  package sud_tanj.com.icare {
    package sud_tanj.com.icare.Backend {
      package sud_tanj.com.icare.Backend.Database {
        class HybridReference {
            {static} # PAPER_OFFLINE_KEY_COLLECTION : String
            - databaseReference : DatabaseReference
            - completionListener : CompletionListener
            {static} - isPersistenceSet : boolean
            + setValue()
            {static} + init()
            + setValue()
            - cacheToFirebase()
            - cacheToPaper()
            + onComplete()
            + HybridReference()
            + getDatabaseReference()
        }
      }
    }
  }
  

  package sud_tanj.com.icare {
    package sud_tanj.com.icare.Backend {
      package sud_tanj.com.icare.Backend.Database {
        abstract class SyncableObject {
            # identification : String
            # timeStamp : Long
            + SyncableObject()
            + toString()
            + SyncableObject()
            + getIdentification()
            + getTimeStamp()
        }
      }
    }
  }
  

  package sud_tanj.com.icare {
    package sud_tanj.com.icare.Backend {
      package sud_tanj.com.icare.Backend.Database {
        class UserInformation {
            {static} + KEY : String
            - name : String
            - email : String
            - developer : Boolean
            + UserInformation()
            + setName()
            + setEmail()
            + setDeveloper()
            + getName()
            + getEmail()
            + getDeveloper()
        }
      }
    }
  }
  

  HybridReference -up-|> CompletionListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
